services:
  grafana:
    user: root
    container_name: 'bmwlab-bmwlabhtmlrender-panel'

    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-11.2.2}
        development: ${DEVELOPMENT:-false}
    ports:
      - 3000:3000/tcp
    network_mode: host
    volumes:
      - ./dist:/var/lib/grafana/plugins/bmwlab-bmwlabhtmlrender-panel
      - ./provisioning:/etc/grafana/provisioning
      - .:/root/bmwlab-bmwlabhtmlrender-panel

    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.bmwlab-bmwlabhtmlrender-panel:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: bmwlab-bmwlabhtmlrender-panel
